/**
 * <p>The sequence of triangle numbers is generated by adding the natural numbers. So the 7<sup>th</sup> triangle number would be 1 + 2 + 3 + 4 + 5 +
 * 6 + 7 = 28. The first ten terms would be:</p>
 * <p class="center">1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...</p>
 * <p>Let us list the factors of the first seven triangle numbers:</p>
 * <blockquote class="monospace"><b> 1</b>: 1<br /><b> 3</b>: 1,3<br /><b> 6</b>: 1,2,3,6<br /><b>10</b>: 1,2,5,10<br /><b>15</b>: 1,3,5,15<br
 * /><b>21</b>: 1,3,7,21<br /><b>28</b>: 1,2,4,7,14,28</blockquote>
 * <p>We can see that 28 is the first triangle number to have over five divisors.</p>
 * <p>What is the value of the first triangle number to have over five hundred divisors?</p>
 *
 * @author Oleg Cherednik
 * @since 19.09.2020
 */
public class Euler {

    public static void main(String... args) {
        System.out.println(Solution.getHighlyDivisibleTriangularNumber(500));
    }
}
